name: Release

permissions: {}

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  integration:
    name: Integration
    uses: ./.github/workflows/integration.yml

  publish:
    name: Publish
    if: ${{ github.repository_owner == 'hideoo' }}
    needs:
      - integration
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          version: 8.10.0

      - name: Install Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: 24.18.0
          package-manager-cache: false
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install

      - name: Publish
        run: pnpm publish --no-git-checks

      - name: Generate changelog
        uses: hideoo/changelogithub-action@9166695d56e3e4bcb74176d7ebf98f4bb18c0882 # v1.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
